name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: wpilib/ubuntu-base:18.04
    name: Build - Linux
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Configure CMake
        run: mkdir build && cd build && cmake ..

      - name: Build
        run: cd build && make -j3

  build-macos:
    runs-on: macos-11.0
    name: Build - macOS
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.3.app

      - name: Configure CMake
        run: mkdir build && cd build && cmake ..

      - name: Build
        run: cd build && make -j3
