name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure and Build
        run: mkdir build && cd build && cmake .. && make -j3
  
  build-macos:
    name: Build - macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure and Build
        run: mkdir build && cd build && cmake .. && make -j3
