name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-20.04
            name: Linux
    
    runs-on: ${{ matrix.os }}
    name: "Build - ${{ matrix.name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure CMake
        run: mkdir build && cd build && cmake ..
      
      - name: Build
        run: cd build && make -j3
