name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure and Build
        run: mkdir build && cd build && cmake .. && make -j3

  build-macos:
    name: Build - macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure and Build
        run: mkdir build && cd build && cmake .. && make -j3

  wpiformat:
    name: "wpiformat"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history and metadata
        run: |
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install clang-format
        run: sudo apt-get update -q && sudo apt-get install clang-format-10
      - name: Install wpiformat
        run: pip3 install wpiformat
      - name: Run
        run: wpiformat -clang 10
      - name: Check Output
        run: git --no-pager diff --exit-code HEAD
