name: CI

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-11.0
    name: Build - macOS
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install OpenCV
        run: brew install opencv

      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.3.app

      - name: Configure CMake
        run: mkdir build && cd build && cmake ..

      - name: Build
        run: cd build && make -j3
