name: CI

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-11.0
    name: Build - macOS
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - run: ls -la /Applications

      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app

      - name: Configure CMake
        run: mkdir build && cd build && cmake .. --GXcode "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"
      
      - name: Build
        run: cd build && xcodebuild
